### PR TITLE
Update ruRU.lua

### PR DESCRIPTION
**Pull request by jammergreek**

### CODE REVIEW

**Comment by funkydude** [comment]
You cannot have the "possible submerge" and the "submerge" bar be the same text.

You also missed the "detect magic" warnings which are half translated.

Thanks!

**Comment by funkydude** [comment]
You didn't fix the submerge bar or the magic message?

**Comment by funkydude** [comment]
`L.possible_submerge_bar` cannot be the same as `L.submerge_bar`

**Comment by jammergreek** [comment]
Changed. Sorry.

**Pull request merged**
