### PR TITLE
Update ruRU.lua

### PR DESCRIPTION
**Pull request by jammergreek**

### CODE REVIEW

**Comment by funkydude** [comment]
Have you verified your translation of the say trigger is what the NPC says? Then paste the entire chat message into the comment (--) next to it

**Comment by funkydude** [comment]
Do you plan on addressing this?

**Comment by jammergreek** [comment]
Hello! Unfortunately, I cannot go to Gnomer.

**Comment by funkydude** [comment]
Ok, I added your other translations. Gonna close this one. Open a new pull request if you end up going there and can get the full message.

**Pull request closed without merging**
