### PR TITLE
Update zhCN.lua

### PR DESCRIPTION
**Pull request by nanjuekaien1**

### CODE REVIEW

**Comment by funkydude** [comment]
Please don't take "creative liberty" with translations. I appreciate that you have a suggestion to improve it, but you should do that by making a GitHub report, or by suggesting it on our DIscord, or direct message me on Discord.

I changed the translation for the chat message `L.detect_magic_warning` to add color like you wanted, and also to turn it into a clickable spell link.
But the translation for `L.detect_magic_missing` is a BigWigs message, so it shouldn't be changed.

**Comment by nanjuekaien1** [comment]
ok

**Comment by funkydude** [comment]
Only if it's in the original translation, like a "quote"

**Comment by nanjuekaien1** [comment]
ty

**Pull request merged**
